-- MySQL Script generated by MySQL Workbench
-- Fri Jun 12 20:55:21 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema project_1
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema project_1
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `project_1` DEFAULT CHARACTER SET utf8 ;
USE `project_1` ;

-- -----------------------------------------------------
-- Table `project_1`.`category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_1`.`category` (
  `idcategory` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idcategory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_1`.`products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_1`.`products` (
  `idproduct` INT NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `price` FLOAT NOT NULL,
  `description` VARCHAR(45) NULL,
  `instock` TINYINT NOT NULL,
  `category_idcategory` INT NOT NULL,
  PRIMARY KEY (`idproduct`, `category_idcategory`),
  INDEX `fk_products_category1_idx` (`category_idcategory` ASC) VISIBLE,
  CONSTRAINT `fk_products_category1`
    FOREIGN KEY (`category_idcategory`)
    REFERENCES `project_1`.`category` (`idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_1`.`steps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_1`.`steps` (
  `idstep` INT NOT NULL,
  `topspeed` INT NULL,
  `occupied` TINYINT NULL,
  `assigned` TINYINT NULL,
  PRIMARY KEY (`idstep`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_1`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_1`.`orders` (
  `idorder` INT NOT NULL,
  `adress` VARCHAR(45) NOT NULL,
  `ordertime` DATETIME NOT NULL,
  `deliverystarttime` DATETIME NULL,
  `deliveryendtime` DATETIME NULL,
  `aantal_shocken` INT NULL,
  `idstep` INT NOT NULL,
  PRIMARY KEY (`idorder`, `idstep`),
  INDEX `fk_orders_steps1_idx` (`idstep` ASC) VISIBLE,
  CONSTRAINT `fk_orders_steps1`
    FOREIGN KEY (`idstep`)
    REFERENCES `project_1`.`steps` (`idstep`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_1`.`waypoints`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_1`.`waypoints` (
  `idwaypoint` INT NOT NULL,
  `longitude` VARCHAR(9) NOT NULL,
  `latitude` VARCHAR(9) NOT NULL,
  `avgspeed` FLOAT NOT NULL,
  PRIMARY KEY (`idwaypoint`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_1`.`order_route`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_1`.`order_route` (
  `order_idorder` INT NOT NULL,
  `waypoints_idwaypoint` INT NOT NULL,
  PRIMARY KEY (`order_idorder`, `waypoints_idwaypoint`),
  INDEX `fk_order_route_order1_idx` (`order_idorder` ASC) VISIBLE,
  CONSTRAINT `fk_order_route_waypoints1`
    FOREIGN KEY (`waypoints_idwaypoint`)
    REFERENCES `project_1`.`waypoints` (`idwaypoint`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_route_order1`
    FOREIGN KEY (`order_idorder`)
    REFERENCES `project_1`.`orders` (`idorder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_1`.`order_items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_1`.`order_items` (
  `orders_idorder` INT NOT NULL,
  `products_idproduct` INT NOT NULL,
  `products_category_idcategory` INT NOT NULL,
  `amount` INT NOT NULL,
  PRIMARY KEY (`orders_idorder`, `products_idproduct`, `products_category_idcategory`),
  INDEX `fk_order_items_products1_idx` (`products_idproduct` ASC, `products_category_idcategory` ASC) VISIBLE,
  CONSTRAINT `fk_order_items_orders1`
    FOREIGN KEY (`orders_idorder`)
    REFERENCES `project_1`.`orders` (`idorder`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_order_items_products1`
    FOREIGN KEY (`products_idproduct` , `products_category_idcategory`)
    REFERENCES `project_1`.`products` (`idproduct` , `category_idcategory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `project_1`.`settings`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `project_1`.`settings` (
  `intervalGPS` INT NOT NULL,
  `latitudeformat` VARCHAR(9) NOT NULL,
  `longitudeformat` VARCHAR(9) NOT NULL,
  `intervalMPU` INT NOT NULL,
  `thresholdMPU` FLOAT NOT NULL)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
